### ISSUE TITLE
[Question] Tabs & Sessions

### ISSUE THREAD

**Issue by voltechs** [kofigumbs/multi#122]
Hello!

Pretty slick project. I was introduced to it via the Nativefier project. Chief complaint with Nativefier is the size of the resulting applications, all using up about 200mb. Gets a little out of hand when you've got 10+ different applications.

I had some questions about Multi after taking it for a spin. I'm a software engineer, and one of the apps I like to have is one for the AWS Console. Unfortunately, Multi does not seem to remember my session, so I have to log in between launches. Am I doing something wrong here?

Additionally, I was wondering if it's possible to allow multiple tabs in the same window? For me, I like to use tabs, but would find a huge performance boost if I all my tabs could be grouped by "app". That is to say, I'd have an AWS Console "Multi" App, and could have multiple tabs in that app. Then I could have another app, let's say, Github.com for example, also with multiple tabs.

Then I could launch/close those as needed. Basically just a fancy "chromeless" WebKit wrapper that remembers sessions/state, including tabs etc. Is that something that is or could be within scope of Multi, and if not, is there something else out there that would fit this use-case?

**Comment by kofigumbs** [comment]
Thanks for checking out the project!

Multi remembers sessions between launches and supports multiple tabs in the same window. All tabs in a window use the same session though. It sounds like you are interested in each tab have a separate session so that you can access separate accounts at once. That feature has been requested in #9.

**Comment by voltechs** [comment]
Hi @kofigumbs thanks for the fast reply! Luckily (?) I'm not actually looking for support for different sessions between tabs, but I could see how some might want that. That's great to hear that the functionality I'm looking for exists!

Just to be clear, I can make a (for example) `AWS Console` "Multi" app, and then hit ⌘T to make a new tab of the same session?

Also, what do I need to do to enable session persistence between launches, because currently it has me logging in each time to AWS when I launch the multi app.

Cheers!

**Comment by voltechs** [comment]
I'm back! I should note, I did all the above on macOS Mojave. I just tried this on my work computer, which is running macOS Ventura, and if you show the tab bar in any given app (at least in so far as ones created with only one "multi" tab via the JSON config from the beginning), a "+" does show up on the far right, and when clicked it does create a new tab from the same page (see screengrab).

![Screenshot 2023-08-01 at 11 08 40](https://github.com/kofigumbs/multi/assets/1700514/6926f55f-9580-4a1e-b94b-52cd0d226480)

**Comment by kofigumbs** [comment]
I think I disabled the "+" button in 3.0 since the behavior (always re-opening the first tab) didn't make much sense. Once there's a workflow for dynamic tabs, it would make sense to connect it to that button.

I think between the two issues linked above, we've tackled both of your questions. I'm going to close this issues, but still feel free to reply if you have other questions.
