### ISSUE TITLE
software license is ambiguous

### ISSUE THREAD

**Issue by sneak** [kofigumbs/multi#37]
The README says that multi is GPLv3, but it also says you should "purchase a license".  This is ambiguous, as the GPL *is* a license.  It also says on your website:

> Multi is licensed, not sold. You can only use Multi if you agree with these usage terms. A Multi license can be used in one of two ways:

This suggests that the software is not GPLv3.

Could you please put a LICENSE file in the repository that clarifies that the software is GPL licensed, if indeed it is?

**Comment by kofigumbs** [comment]
I see what you're saying about the two meanings of the word "license". I will clarify the website language, but I need to research if there's a better term. The website is only using "license" to mean something like "proof of purchase". I aim to grant proof-or-purchase-holders priority support when they open GitHub issues. Also, that proof of purchase removes the trial message from the Multi product.

The wording you quoted is talking about the "proof of purchase" and not the source code. The source code is GPLv3, per the COPYING file. (Typically with GPL you put the license contents in `./COPYING` instead of `./LICENSE`.)

Hope that clarifies. Feel free to reply additional questions—I'm gonna close since I don't plan to take action in the multi repo.

**Comment by sneak** [comment]
You should avoid the word “purchase” if the software is free software (GPL licensed).  You may wish to use the word “donation” or “support” instead, for clarity. :)
