### ISSUE TITLE
Can't sign in to a second team on slack

### ISSUE THREAD

**Issue by llimllib** [kofigumbs/multi#44]
My slack multi has this config, dead standard:

```
$ cat /Applications/Multi/Slack\ Safari.app/Contents/Resources/config.json
{
  "tabs": [
    {
      "title": "Slack Safari",
      "url": "https://app.slack.com/client"
    }
  ]
}
```

It works fine for the one team that I am signed in with, and I like it so I want to sign in to another team.

Unfortunately, it pops open system Safari when I click `Add workspaces -> sign in to another team`, and when I add a team, it doesn't redirect back to the Multi app. Demo: https://www.youtube.com/watch?v=9jFgToEW4Lc&feature=youtu.be

(nothing happens after I click "allow")

Any ideas for how to log into a second team?

**Comment by kofigumbs** [comment]
Hi Bill, thanks for the detail--the video was helpful! Ultimately the easiest way to do this is by using separate Multi tabs (that's how I use Multi actually):

```json
{
  "tabs": [
    {
      "title": "Org 1",
      "url": "https://XXX.slack.com"
    },
    {
      "title": "Org 2",
      "url": "https://YYY.slack.com"
    }
  ]
}
```

You would replace your workspace `XXX` and `YYY` with your workspace subdomains.

For Slack in particular, I think getting multiple orgs in the same Multi tab is more trouble than it's worth. The Slack desktop app is very similar to the web app, but not identical. The workspace switcher is an example of a component that doesn't seem to exist in the web app. If you are signed into multiple Slack orgs in your browser, you wouldn't see them all in a column on the left-hand side. Instead you get a menu dropdown near the one that you navigated to in your video. The lack of the dedicated switcher was reason enough for me to stop going down the single tab route.

If for some reason you were really intent still on getting this to work in a single Multi tab, I think you'd want to use [custom JS](https://github.com/kofigumbs/multi/blob/2.x/Documentation/CUSTOM-JS.md) to make it so that Slack never opened the browser window in the first place. Instead, you'd want that Sign In prompt to open in the Multi app itself, so that there is no deep linking involved. I really don't suggest this option, but let me know if you'd like more clarity on how to pursue it.

**Comment by llimllib** [comment]
Thank you for the detailed answer! Figuring out the JS to do that sounds satisfying, but I'm far too lazy for that.
