### ISSUE TITLE
multi opens up in inconvenient locations

### ISSUE THREAD

**Issue by llimllib** [kofigumbs/multi#45]
I have an external monitor as my primary monitor. When I open up multi apps, they often up almost completely off the desktop, with just a tiny bit visible.

Attached is an example of where a multi app started itself up:

<img width="512" alt="multibug" src="https://user-images.githubusercontent.com/7150/98966578-71c26300-24d9-11eb-8c09-ed095c101ec2.png">

multi apps should ideally start themselves where they were most recently located

**Comment by kofigumbs** [comment]
Hey there, can you confirm that you're on the latest version (2.0.8)? I thought this was fixed in https://github.com/kofigumbs/multi/commit/b505fa686b0ee45da1d3f4d1bf01a70d4ee2c34a which is why I ask. Also, are you having to this experience every time you open the same Multi app? When you reopen a Multi app, it should remember window coordinate that you last moved it to.

**Comment by llimllib** [comment]
ah, no, now I've upgraded - will re-open if I see it again. Apologies.

(Also, would love some sort of sparkle updater instead of having to find the release page to update)

**Comment by kofigumbs** [comment]
No apology necessary—incorporating Sparkle was actually on my TODO list! I plan to include it when I next get a chance to ship batch of updates. Glad this one is sorted for you tho.
