### ISSUE TITLE
Issue loading when trying to set a Google Meets URL

### ISSUE THREAD

**Issue by helpingharry** [kofigumbs/multi#55]
When I set a Google meets URL it just loads endlessly. I saw the custom JS mentioned for other Google products and tried to set that locally, but unfortunately that doesn't look like its done the job. I was just wondering if you were aware of any other issues with this?

**Comment by kofigumbs** [comment]
Hey there! Probably not what you want to hear, but I wouldn't expect Google Meets (or any video call site) to work in Multi right now. Issue #16 tracks this, so you could drop a 👍  there as an informal up vote.

Gonna close this issue since it's tracked elsewhere, but if you think I'm barking up the wrong tree, feel free to reply/reopen.
