### ISSUE TITLE
Google Sheets errors

### ISSUE THREAD

**Issue by gingerbeardman** [kofigumbs/multi#59]
When viewing a spreadsheet in Google Sheets I get this error in Multi:

<img width="439" alt="Screen shot 2021-01-11 at 12 44 12" src="https://user-images.githubusercontent.com/49612/104184092-d717cf00-540a-11eb-874a-d230b7cb2611.png">

Clicking OK I get get a second error exactly the same. 

Clicking OK on the second error leaves me with this in the page:

<img width="452" alt="Screen shot 2021-01-11 at 12 45 57" src="https://user-images.githubusercontent.com/49612/104184194-fd3d6f00-540a-11eb-8a1d-40be7ced81f2.png">

Clicking Reload repeats these.

Any help appreciated.

**Comment by kofigumbs** [comment]
Thanks for the report! I could duplicate the issue and found that it works fine when I imitate Chrome instead of Safari. I guess Google is doing something tricky on the backend. Anyways, I added the `userAgent` config option in [v2.1.1](https://github.com/kofigumbs/multi/releases/tag/v2.1.1) which should let you imitate any browser you like. This is the config I used to imitate Chrome and get things working:

```json
{
  "tabs": [
    {
      "title": "Sheet test",
      "url": "https://docs.google.com/spreadsheets/d/1YroXgCX08Y_AGFrAHPb5dtLiSpLzlCfECTpLzvwC4ac/edit?usp=sharing",
      "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
    }
  ]
}
```

**Comment by gingerbeardman** [comment]
Thanks!
