### ISSUE TITLE
Support find in page (⌘+F)

### ISSUE THREAD

**Issue by wilsonehusin** [kofigumbs/multi#65]
I would love for Multi apps to support find in page through ⌘+F, just like the usual browser.

My primary use case is on a dedicated, focused window for documentation (e.g. [`pkg.go.dev`](https://pkg.go.dev)).

I mean ideally I want something like [fuzzy-finder](https://github.com/junegunn/fzf), but I will settle with regular find in page 😄

**Comment by kofigumbs** [comment]
Hey Wilson, thanks for checking out Multi. I wrote a Custom JS snippet that gets you a very minimal Find shortcut/functionality: https://github.com/kofigumbs/multi#find-in-page

I’m sure it could be made better, and if you do end up getting fuzzy search to work, I’d love to hear about it. Gonna close this issue out since I don’t plan to change anything to the Swift code here.

**Comment by wilsonehusin** [comment]
apologies for not finding it in the README before i opened the issue and thanks for the reply! loving Multi
