### ISSUE TITLE
Distribute standalone multi apps

### ISSUE THREAD

**Issue by toomim** [kofigumbs/multi#68]
If I create a chat app with multi, is there a way I can package up the .app file and send it to a friend to run on their computer? Can I create an app with multi and let people download it from my website?

It seems that the apps created are still dependent upon some files within /Applications/Multi.app. Is there a way to bundle those dependencies with the new app? Do we run into code signing issues?

**Comment by kofigumbs** [comment]
Yup, I think codesigning would be the main issue here. Since the generated Multi apps originate from your machine, only your macOS instance knows to trust them -- that's my mental model of how it works at least.

If I were in your scenario, and I were trying to distribute an app to a _small group_ of friends, then I'd probably just have them install Multi and paste the JSON you provide. You could even write a short script that uses `brew` and the Multi CLI to do all the work for them!

For a _larger group_, I think you'd want to look into forking Multi and hardcoding your site, or implementing your own little web app wrapper. It's pretty simple to make a Swift app that just launches a single `NSView` (which would be a `WKWebView` in your case): https://kofi.sexy/blog/multi#approach

(Closing this for book-keeping reasons, but we can continue this conversation if you have other questions.)

**Comment by toomim** [comment]
Ah, that makes sense! Thank you very much for taking the time to explain this. It's quite insightful and helps me understand how multi sits in relation to browsers, electron apps, and standalone apps with a webview.
