### ISSUE TITLE
Support for not quitting the app when closing the window

### ISSUE THREAD

**Issue by kLy** [kofigumbs/multi#73]
This is often the desired behaviour for most apps. For example when I close the Mail or the Slack window, it just closes the window, but the app is still running. When I click on the dock icon again, Mail or Slack would show the window as it previously was, without needing to start up again or reload anything. One can still quit the app using Cmd+Q.

This would allow the Multi apps to behave more like what is expected of a Mac app.

**Comment by kofigumbs** [comment]
That would be great! I'd be happy to help you (or anyone else interested) in getting that PR going. Here are some quick notes if you'd like to take a look around:

- [Program+NSApplicationDelegate.swift](https://github.com/kofigumbs/multi/blob/2.x/Sources/Shared/Program%2BNSApplicationDelegate.swift) is where the current hard-coded behavior lives.
- This behavior will need to be configurable, which means that it needs a corresponding property on the [Config](https://github.com/kofigumbs/multi/blob/2.x/Sources/Runtime/Config.swift) global (`openNewWindowsInBackground` is an example of a property that works this way).
- Currently, the hard-coded delegate is shared between the user-created apps and Multi.app. Instead, we'd probably need to pass in a delegate to [Program.start](https://github.com/kofigumbs/multi/blob/2.x/Sources/Shared/Program.swift#L42-L52) so that user-created apps can access the Config global.

This commit is probably the closest example of how to add this kind of config: https://github.com/kofigumbs/multi/commit/408d823f565d786b7d5dfa941ff21fda3b8d8a6d#diff-28428d24095d20ba23fc210c3d40ed4ea187cdeb552ca4c3ee789a346926865a
