### ISSUE TITLE
better.fyi adblocker is deprecated/discontinued

### ISSUE THREAD

**Issue by PivotMasterNM** [kofigumbs/multi#79]
according to their website, the adblocker has been discontinued since mid December 21.

**Comment by kofigumbs** [comment]
Oof, that's unfortunate. Thanks for pointing me to that. I don't think this really affects things for Multi currently, since the blocklist itself is a static asset.

Long-term I'm thinking of removing Multi's default blocklist, and just providing a config option for using your own. This is partially discussed in #62 -- I'm going to close this issue since that one already acts as a good reminder for me.
