### ISSUE TITLE
transparent titlebar

### ISSUE THREAD

**Issue by Brin-o** [kofigumbs/multi#80]
hi,
is it possible to create a transparent titlebar? or would it be possible to implement this as a feature?

some other, paid, apps that for creating webapps allow you to do that and it adds a lot of the aesthetics of an app if it does not use the standard white/dark background imo.

Here is a comparison of untie and multi
<img width="1555" alt="image" src="https://user-images.githubusercontent.com/49071768/161393301-74740b26-4448-408c-8bdd-bc02bfccf2f6.png">

thank you for making such a great tool :)

**Comment by vanyauhalin** [comment]
Look at #77.

**Comment by kofigumbs** [comment]
I agree that this aesthetic is much nicer; I just haven't come across a way to implement it without sacrificing the macOS native tabs. It looks like you only have a single tab, so Nativifier might work for what you're trying to do. They have a ["frameless window" configuration option](https://github.com/nativefier/nativefier/blob/master/API.md#title-bar-style). There are other trade-offs though since Nativifier is an Electron-based project.

Going to close this particular issue as a duplicate to #77.
