### ISSUE TITLE
Webkit Version not being detected

### ISSUE THREAD

**Issue by PivotMasterNM** [kofigumbs/multi#87]
after the most Recent update, Multi has set my Webkit to something outdated or false. Updated via homebrew. - v. 2.2.0

<img width="773" alt="image" src="https://user-images.githubusercontent.com/59060318/181261876-a3b73b3e-9178-4b31-8eb5-20600afb72bd.png">

<img width="227" alt="image" src="https://user-images.githubusercontent.com/59060318/181262014-22454d25-288b-4a95-9263-b280d8c256bf.png">
<img width="288" alt="image" src="https://user-images.githubusercontent.com/59060318/181262090-a0807951-2647-4d1f-ae7b-37c04cb339ca.png">

glad to troubleshoot if I am missing something or you would like me to test something :)

**Comment by kofigumbs** [comment]
Before 2.2.0, Multi had a hard-coded user-agent that made it appear like Safari. The problem though, was that it was hard-coded and didn't reflect the various WebKit versions that folks actually had installed. See #84. v2.2.0 actually made the user-agent _more_ honest to your system's version. I had a feeling this would break some sites since that's why it was added in the first place. Unfortunately, it still seemed like a better solution than continuing to hard-code a fake user-agent.

You can fix your Multi app by setting the `userAgent` config yourself. I recommend using whatever your Safari reports. For me, the config would look like this:

```json
{
  "tabs": [
    {
      "title": "WhatsApp-native",
      "url": "https://web.whatsapp.com",
      "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15"
    }
  ]
}
```

**Comment by PivotMasterNM** [comment]
ahhh, good to know. You're absolutely right with your implementation, thanks for the tip! Overlooked that I could set the userAgent myself. Thanks!

**Comment by zenspider** [comment]
If #84 was fixed in 2.2.0 then something is still broken as slack (sans custom user agent in the config) is still reporting that the browser is unsupported (I wish it would say what it thought it was). Should this be reopened?

I'm testing out a number of these apps to find a replacement for flotato and several of them have worked fine with slack, so the fact that this one does not hints that either something didn't make it into the release or still needs tweaking.

**Comment by kofigumbs** [comment]
@zenspider if Slack (or any site) chooses to disable functionality based on user-agent, then you’ll have to provide a fake user-agent to workaround that. Multi used to provide a default fake, which is probably what those other apps do. Multi will no longer provide a fake value, and it takes 1 line to set it yourself if needed. Since the default is sensible and the workaround is easy, I don’t plan to make further revisions in this area.

**Comment by zenspider** [comment]
Slack works fine in safari as-is. So if this is now sending an up to date user agent string from/as safari, I would expect it to work. Is that not the case?

**Comment by kofigumbs** [comment]
@zenspider that is not the case. User agent headers contain more than just the WebKit version. The best way to see the difference for yourself would be to compare the user-agent header in your Safari version to the one from Multi.
